# Import data and packages into notebook

In [13]:
import pandas as pd

In [2]:
profiles = pd.read_csv('profiles.csv')

# Load and check dataset

In [3]:
profiles.head()

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22,a little extra,strictly anything,socially,never,working on college/university,about me:<br />\n<br />\ni would love to think...,currently working as an international agent fo...,making people laugh.<br />\nranting about a go...,"the way i look. i am a six foot half asian, ha...",...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35,average,mostly other,often,sometimes,working on space camp,i am a chef: this is what that means.<br />\n1...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38,thin,anything,socially,NaN,graduated from masters program,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23,thin,vegetarian,socially,NaN,working on college/university,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29,athletic,NaN,socially,never,graduated from college/university,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at:<br />\nhttp://bag...,i smile a lot and my inquisitive nature,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single

In [4]:
profiles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59946 entries, 0 to 59945
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          59946 non-null  int64
 1   body_type    54650 non-null  object
 2   diet         35551 non-null  object
 3   drinks       56961 non-null  object
 4   drugs        45866 non-null  object
 5   education    53318 non-null  object
 6   essay0       54458 non-null  object
 7   essay1       52374 non-null  object
 8   essay2       50308 non-null  object
 9   essay3       48470 non-null  object
 10  essay4       49409 non-null  object
 11  essay5       49096 non-null  object
 12  essay6       46175 non-null  object
 13  essay7       47495 non-null  object
 14  essay8       40721 non-null  object
 15  essay9       47343 non-null  object
 16  ethnicity    54266 non-null  object
 17  height       59943 non-null  float64
 18  income       59946 non-null  int64
 19  job          51748 non-null  object
 20  last_online  59946 non-null  object
 21  location     59946 non-null  object
 22  offspring    24385 non-null  object
 23  orientation  59946 non-null  object
 24  pets         40025 non-null  object
 25  religion     39720 non-null  object
 26  sex          59946 non-null  object
 27  sign         48890 non-null  object
 28  smokes       54434 non-null  object
 29  speaks       59896 non-null  object
 30  status       59946 non-null  object
dtypes: float64(1), int64(2), object(28)
memory usage: 14.2+ MB

In [5]:
profiles.describe()

                age        height          income
count  59946.000000  59943.000000    59946.000000
mean      32.340290     68.295281    20033.222534
std        9.452779      3.994803    97346.192104
min       18.000000      1.000000       -1.000000
25%       26.000000     66.000000       -1.000000
50%       30.000000     68.000000       -1.000000
75%       37.000000     71.000000       -1.000000
max      110.000000     95.000000  1000000.000000

# Preprocess Data

For many of the columns in **profiles**, the labels assigned to them make it unclear what information they feature. I will start the preprocessing by changing the names of the following columns:

- *orientation* will become *sexual_orientation*
- *sign* will become *astrological_sign*
- *speaks* will become *languages*
- *status* will become *marital_status*

In [6]:
profiles.rename(columns={"orientation": "sexual_orientation", "sign": "astrological_sign", "speaks": "languages", "status": "marital_status"})

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,sexual_orientation,pets,religion,sex,astrological_sign,smokes,languages,marital_status
0,22,a little extra,strictly anything,socially,never,working on college/university,about me:<br />\n<br />\ni would love to think...,currently working as an international agent fo...,making people laugh.<br />\nranting about a go...,"the way i look. i am a six foot half asian, ha...",...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35,average,mostly other,often,sometimes,working on space camp,i am a chef: this is what that means.<br />\n1...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38,thin,anything,socially,NaN,graduated from masters program,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23,thin,vegetarian,socially,NaN,working on college/university,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29,athletic,NaN,socially,never,graduated from college/university,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at:<br />\nhttp://bag...,i smile a lot and my inquisitive nature,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59941,59,NaN,NaN,socially,never,graduated from college/university,"vibrant, expressive, caring optimist. i love b...",the happiest times have been when life came to...,i make an outstanding osso bucco. i am also ve...,"i am told that people notice my smile, eyes an...",...,"oakland, california",has kids,straight,has dogs,catholicism but not too serious about it,f,cancer and it&rsquo;s fun to think about,no,english,single
59942,24,fit,mostly anything,often,sometimes,working on college/university,i'm nick.<br />\ni never know what to write ab...,currently finishing school for film production...,"<a class=""ilink"" href=""/interests?i=filmmaking...","dude, i don't know.",...,"san francisco, california",doesn&rsquo;t have kids,straight,likes dogs and likes cats,agnosticism,m,leo but it doesn&rsquo;t matter,no,english (fluently),single
59943,42,average,mostly anything,not at all,never,graduated from masters program,"hello! i enjoy traveling, watching movies, and...","i'm a civil engineer, who enjoys helping the c...",- looking at things objectively<br />\n- getti...,i'm quiet until i get used to the environment ...,...,"south san francisco, california",doesn&rsquo;t have kids,straight,NaN,christianity but not too serious about it,m,sagittarius but it doesn&rsquo;t matter,no,english (fluently),single
59944,27,athletic,mostly anything,socially,often,working on college/university,"""all i have in this world are my balls and my ...","following my dreams...<br />\n""you got a dream...",listening,it used to be the hair until i mowed it off bu...,...,"san francisco, california","doesn&rsquo;t have kids, but wants them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,leo and it&rsquo;s fun to think about,trying to quit,"english (fluently), spanish (poorly), chinese ...",single
59945,39,average,NaN,socially,NaN,graduated from masters program,"is it odd that having a little ""enemy"" status ...",i work with elderly people (psychotherapy and ...,i'm a great bullshitter. i don't know what it ...,"either that i am funny/sarcastic, or that i am...",...,"san francisco, california",NaN,gay,likes dogs and likes cats,catholicism and laughing about it,m,gemini and it&rsquo;s fun to think about,sometimes,english,single

A decision tree classification model will be used to predict the diets of the user profiles where that information is missing. Decision trees have the advantage of handling missing values in a dataset well and can be used in problems where instances must be assigned to three or more classes.

To create this decision tree model, I need a data point with the following features:
- What is the religion of the user?
- What kind of body type do they have?
- What is their level of education?

These four features, along with the *diet* variable, need to undergo cleaning before we conduct any work with them to create the decision tree. Let's begin with the *diet* variable as it is the focus of our question.

In [15]:
profiles.diet.nunique()

18

In [16]:
profiles.diet.unique()

array(['strictly anything', 'mostly other', 'anything', 'vegetarian', nan,
       'mostly anything', 'mostly vegetarian', 'strictly vegan',
       'strictly vegetarian', 'mostly vegan', 'strictly other',
       'mostly halal', 'other', 'vegan', 'mostly kosher',
       'strictly halal', 'halal', 'strictly kosher', 'kosher'],
      dtype=object)

There are 18 unique categories of diet. These diets range from 'anything' to 'vegan' and include diets connected to religious practice like 'kosher' and 'halal'. All of these diets are further broken down by the qualifiers 'strictly' and 'mostly'. This is quite messy and leaves us with several outcomes for the decision tree. To reduce the number of outcomes, these categories will be reduced into each individual diet. For instance, 'mostly vegetarian', 'vegetarian', and 'strictly vegetarian' will be organized into one category, 'vegetarian', and so on.

In [17]:
profiles['dietsCleaned'] = profiles.diet.str.split().str.get(1)
print(profiles.dietsCleaned.nunique())
print(profiles.dietsCleaned.unique())

6
['anything' 'other' nan 'vegetarian' 'vegan' 'halal' 'kosher']

Now the number of diets has been reduced to 6 categories.

Let's go ahead and do the same to the four features.

In [18]:
print(profiles.religion.nunique())
print(profiles.religion.unique())

45
['agnosticism and very serious about it'
 'agnosticism but not too serious about it' nan 'atheism' 'christianity'
 'christianity but not too serious about it'
 'atheism and laughing about it' 'christianity and very serious about it'
 'other' 'catholicism' 'catholicism but not too serious about it'
 'catholicism and somewhat serious about it'
 'agnosticism and somewhat serious about it'
 'catholicism and laughing about it' 'agnosticism and laughing about it'
 'agnosticism' 'atheism and somewhat serious about it'
 'buddhism but not too serious about it'
 'other but not too serious about it' 'buddhism'
 'other and laughing about it' 'judaism but not too serious about it'
 'buddhism and laughing about it' 'other and somewhat serious about it'
 'other and very serious about it' 'hinduism but not too serious about it'
 'atheism but not too serious about it' 'judaism'
 'christianity and somewhat serious about it'
 'hinduism and very serious about it' 'atheism and very serious about it'
 'judaism and laughing about it' 'christianity and laughing about it'
 'hinduism and laughing about it' 'buddhism and somewhat serious about it'
 'islam and very serious about it' 'islam' 'hinduism'
 'judaism and somewhat serious about it'
 'catholicism and very serious about it'
 'judaism and very serious about it'
 'hinduism and somewhat serious about it'
 'islam but not too serious about it' 'buddhism and very serious about it'
 'islam and laughing about it' 'islam and somewhat serious about it']

In [19]:
profiles['religionCleaned'] = profiles.religion.str.split().str.get(0)
print(profiles.religionCleaned.nunique())
print(profiles.religionCleaned.unique())

9
['agnosticism' nan 'atheism' 'christianity' 'other' 'catholicism'
 'buddhism' 'judaism' 'hinduism' 'islam']

In [21]:
print(profiles.body_type.nunique())
print(profiles.body_type.unique())

12
['a little extra' 'average' 'thin' 'athletic' 'fit' nan 'skinny' 'curvy'
 'full figured' 'jacked' 'rather not say' 'used up' 'overweight']

*body type* does not need further breaking down so we will leave that feature as is.

In [22]:
print(profiles.education.nunique())
print(profiles.education.unique())

32
['working on college/university' 'working on space camp'
 'graduated from masters program' 'graduated from college/university'
 'working on two-year college' nan 'graduated from high school'
 'working on masters program' 'graduated from space camp'
 'college/university' 'dropped out of space camp'
 'graduated from ph.d program' 'graduated from law school'
 'working on ph.d program' 'two-year college'
 'graduated from two-year college' 'working on med school'
 'dropped out of college/university' 'space camp'
 'graduated from med school' 'dropped out of high school'
 'working on high school' 'masters program' 'dropped out of ph.d program'
 'dropped out of two-year college' 'dropped out of med school'
 'high school' 'working on law school' 'law school'
 'dropped out of masters program' 'ph.d program'
 'dropped out of law school' 'med school']

In [27]:
education_levels = {'high school': ['graduated from high school', 'dropped out of college/university', 'dropped out of two-year college', 'high school'], 
 'in high school': 'working on high school', 
 'post-secondary': ['graduated from college/university', 'college/university', 'two-year college', 'graduated from two-year college', 
                    'dropped out of med school', 'dropped out of masters program', 'dropped out of law school'], 
 'in post-secondary': ['working on college/university', 'working on two-year college'], 
 'graduate program': ['graduated from masters program', 'graduated from ph.d program', 'graduated from law school', 'graduated from med school', 
                      'masters program', 'dropped out of ph.d program', 'law school', 'ph.d program', 'med school'], 
 'in graduate program': ['working on masters program', 'working on ph.d program', 'working on med school', 'working on law school'], 
 'other': ['graduated from space camp', 'dropped out of space camp', 'space camp', 'dropped out of high school'], 'in other': 'working on space camp'}

In [28]:
profiles['educationCleaned'] = profiles.education.map(education_levels)
print(profiles.head())

   age       body_type               diet    drinks      drugs  \
0   22  a little extra  strictly anything  socially      never
1   35         average       mostly other     often  sometimes
2   38            thin           anything  socially        NaN
3   23            thin         vegetarian  socially        NaN
4   29        athletic                NaN  socially      never

                           education  \
0      working on college/university
1              working on space camp
2     graduated from masters program
3      working on college/university
4  graduated from college/university

                                              essay0  \
0  about me:<br />\n<br />\ni would love to think...
1  i am a chef: this is what that means.<br />\n1...
2  i'm not ashamed of much, but writing public te...
3          i work in a library and go to school. . .
4  hey how's it going? currently vague on the pro...

                                              essay1  \
0  currently working as an international agent fo...
1  dedicating everyday to being an unbelievable b...
2  i make nerdy software for musicians, artists, ...
3          reading things written by old dead people
4                         work work work work + play

                                              essay2  \
0  making people laugh.<br />\nranting about a go...
1  being silly. having ridiculous amonts of fun w...
2  improvising in different contexts. alternating...
3  playing synthesizers and organizing books acco...
4  creating imagery to look at:<br />\nhttp://bag...

                                              essay3  ...  \
0  the way i look. i am a six foot half asian, ha...  ...
1                                                NaN  ...
2  my large jaw and large glasses are the physica...  ...
3                  socially awkward but i do my best  ...
4            i smile a lot and my inquisitive nature  ...

                                   religion sex  \
0     agnosticism and very serious about it   m
1  agnosticism but not too serious about it   m
2                                       NaN   m
3                                       NaN   m
4                                       NaN   m

                                 sign     smokes  \
0                              gemini  sometimes
1                              cancer         no
2  pisces but it doesn&rsquo;t matter         no
3                              pisces         no
4                            aquarius         no

                                              speaks     status isVegan  \
0                                            english     single       0
1  english (fluently), spanish (poorly), french (...     single       0
2                               english, french, c++  available       0
3                           english, german (poorly)     single       0
4                                            english     single       0

   dietsCleaned  religionCleaned educationCleaned
0      anything      agnosticism              NaN
1         other      agnosticism              NaN
2           NaN              NaN              NaN
3           NaN              NaN              NaN
4           NaN              NaN              NaN

[5 rows x 35 columns]